### ISSUE TITLE
Mapa Mental - Web 3.0

### ISSUE THREAD

**Issue by IsaHuerta23** [SistemasTecTlaxiaco/mapa-mental-web-3-IsaHuerta23#1]
![Mapa Mental - Web 3 0](https://user-images.githubusercontent.com/79929235/161414876-2352069d-5cd3-41f9-a0d5-66617a775d2b.png)

**Comment by DuilioAquino10** [comment]
CALIFICACIÓN: 20/20.

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
